### ISSUE TITLE
Create list of EnvVars used

### ISSUE THREAD

**Issue by SocksTheWolf** [SocksTheWolf/AntiScamBot#24]
This should be done to make it clear for anyone that decides to spin up an instance of the bot, what flags they need to set to have a working instance

**Comment by avaankha** [comment]
Hey I'm interested in helping out with the project. Any rules when it comes to contributing?

**Comment by SocksTheWolf** [comment]
@avaankha thats awesome! I’ll be drafting some contribution guidelines soon as a part of #26. For a task like this one, there really isn’t much other than just making a list

**Comment by avaankha** [comment]
It looks like I need write access to create branches from main. Could I get permissions to do so?

**Comment by SocksTheWolf** [comment]
@avaankha you should be able to open pull requests for the project, doing so would allow us to merge in changes.
