### ISSUE TITLE
Changing the name of the bot

### ISSUE THREAD

**Issue by SocksTheWolf** [SocksTheWolf/AntiScamBot#33]
Currently, the two names in the system are:

"BEGONE, SCAMMER" and "Commission Scammer Banner".

Both of these names are not very great, and we should probably determine a better name before verification, as that will permanently lock in our bot's user name as [per this support article](https://support-dev.discord.com/hc/en-us/articles/6130147813271-How-To-Change-My-Verified-Bot-s-Name).

Will need to also update the screenshot [seen here](https://theantiscamgroup.com/install) once names have been chosen.

**Comment by SocksTheWolf** [comment]
Instead of "Commission Scammer Banner", how about "The Antiscam Bot"?

**Comment by DocNurseTheLion** [comment]
"Britney"

**Comment by SocksTheWolf** [comment]
> "Britney"

No one is going to know that reference, lol.

**Comment by SocksTheWolf** [comment]
Currently enjoying the ScamGuard name, I've applied it to the project portal, and the bot has been using it recently.

I think it's fairly clear what this does, it doesn't appear to conflict with any other discord bot names.
