### ISSUE TITLE
Add thread link information to ban data

### ISSUE THREAD

**Issue by SocksTheWolf** [SocksTheWolf/AntiScamBot#36]
Specifically, this should add either a new few columns into the banned accounts table or should be an entire separate table.

The goal of this is to populate the information with links to report threads (store a list of thread ids, not the actual links). The bot can resolve those thread ids when it generates said embed data.

**Comment by user4752** [comment]
once #39 has been confirmed, this can be easily done in a v3 database migration and can be done in multiple ways;

one example is a basic one-to-many table with a relationship between an entry in the ban table referencing a discord user id to a thread id, with multiple entries, one per unique thread / reporter.

Depending on intentions this can be a forced relationship, thus requiring a ban to exist prior to the linked threads, or a separate object which would allow reported thread ids to be referenced to a user id without a ban needing to exist.

**Comment by SocksTheWolf** [comment]
Based on potential usage cases so far, I think an implementation would not require the userid in question to be on the ban list, as we could have suspicious reports about a user without them being banned.

**Comment by user4752** [comment]
With remote reporting with evidence now available, and the data being posted into ConfigData['ReportChannel'] via BotMain: PostScamReport(), is this issue still something which needs to be stored in the database?

**Comment by SocksTheWolf** [comment]
I think this would still be good to be able to present information on the scammers and would also increase trust among server operators.

**Comment by SocksTheWolf** [comment]
I think when we register a ban, we're going to just add the field to the ban object, and then can create a discord snowflake link to the channel thread for more information. We can add that object to any ban embed that's created. The thread itself can be pulled from the interaction during a ban approve.

**Comment by SocksTheWolf** [comment]
Building upon this, I'm going to just add a field to the ban table, and it'll be whenever someone is banned, to include an thread index id
