### ISSUE TITLE
Update documentation on commands

### ISSUE THREAD

**Issue by SocksTheWolf** [SocksTheWolf/AntiScamBot#46]
Currently there is no documentation regarding the new scamguard slash commands for reporting/checking bans. This should be properly documented on the website!

**Comment by Izaan17** [comment]
I would like to help out! Please give me more information!

**Comment by user4752** [comment]
Would comments in code documenting function code flow be wanted in this as well, or a markdown file / repo wiki page?

**Comment by SocksTheWolf** [comment]
I think it's going to make more sense to have it as a markdown / wiki page. idk if I want to also have a wiki involved as well.

**Comment by SocksTheWolf** [comment]
Closing, page created here https://github.com/SocksTheWolf/AntiScamBot/wiki/Command-Documentation
