### ISSUE TITLE
Refactor: Database Schema

### ISSUE THREAD

**Issue by SocksTheWolf** [SocksTheWolf/AntiScamBot#7]
This requires tweaking the database to migrated to one that has better typing/formatting rules. Right now, it's kind of a mess, and even worse if we ever have to upgrade the server.

Look into ways to potentially make this easier to work with that can also build queries. There are a few python libraries that can help.

**Comment by SocksTheWolf** [comment]
We might want to consider moving the database system to something that Railways supports as per #10.

Railways supports ([PostgreSQL](https://docs.railway.app/databases/postgresql), [MySQL](https://docs.railway.app/databases/mysql), [MongoDB](https://docs.railway.app/databases/mongodb), & [Redis](https://docs.railway.app/databases/redis)).

We would have to choose one from this list.

**Comment by SocksTheWolf** [comment]
Dropping above comment. I was under the impression Railways pricing worked on the same system as Digital Ocean, and it does not. It’s actually potentially more expensive.

**Comment by SocksTheWolf** [comment]
I’m wondering if this ticket should be blocked on having the unit testing solidified first #19

**Comment by SocksTheWolf** [comment]
Look into sqlalchemy:

* https://docs.sqlalchemy.org/en/20/dialects/sqlite.html
* https://realpython.com/python-sqlite-sqlalchemy/#working-with-sqlalchemy-and-python-objects

**Comment by user4752** [comment]
Partially implemented conversion to sqlalchemy here:
https://github.com/SocksTheWolf/AntiScamBot/compare/main...user4752:AntiScamBot:db-refactor

ScamBotDatabase class is 90% converted; still need to update Discord.py to accept the new data format being returned

Will make future pull request when complete

**Comment by SocksTheWolf** [comment]
@user4752 skimmed this so far, lots of progress here. Looking forward to reviewing the pr!
